# Generated by Django 3.1.2 on 2020-10-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_auto_20201025_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='contact_no',
            field=models.CharField(default='', max_length=20),
        ),
    ]
