# Generated by Django 3.1.2 on 2020-10-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_auto_20201029_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='img',
            field=models.ImageField(default='', upload_to='yoga/trainer'),
        ),
    ]
