# Generated by Django 3.1.2 on 2020-10-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0007_trainer_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoga',
            name='contact_no',
            field=models.CharField(default='', max_length=20),
        ),
    ]
