# Generated by Django 3.1.2 on 2020-10-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0009_yoga_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yoga',
            name='loc',
        ),
    ]
