# Generated by Django 3.1.2 on 2020-10-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0012_remove_yoga_loc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trainer',
            new_name='Guru',
        ),
    ]
