# Generated by Django 3.1.2 on 2020-10-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0013_auto_20201031_0938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingLevel',
            new_name='TrainingLevels',
        ),
    ]
